typography_spectrum: 0.42946447408758104
color:
  brandStrength: 0.2887887437827885
  lightness: 0.9076210898347199
  saturation: 0.2522584747057408
  rhythmicContrast: 0.46687114029191434
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
layout_spectrum: 0.47440683003515005
author:
  name: Perzen Patel
  email: perzen@bawibride.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/638733ca-3ab8-4a72-96c2-28cd5ebd0a7f.png
name: Bawi Bride Kitchen
navigation:
  - name: What We Do
    id: b36a9d1f-f1a1-46fe-a1d0-b99767ae736b
    type: content
  - name: Party Catering Menu
    id: d46faf6b-f6b1-4e7e-9b9d-7a63b0156230
    type: content
  - name: Order Lunch Online!
    id: afc8d6c7-d6b8-4dfb-8649-79a7a0fe790c
    type: content
  - name: Ready to Cook
    id: a8ce6648-d736-4a9a-9d77-2fd3eceb603b
    type: content
  - name: Parsi Experiences
    id: b8d7c180-89b6-4627-8a8c-5785876f97c4
    type: content
  - name: The Bawi Bride Story
    id: a040c37c-0fe0-479b-af49-cb1aa95d84bf
    type: content
title: Delicious Parsi Food
description: Taste the Love. Love the Taste
