typography_spectrum: 0.878828494111076
color:
  brandStrength: 0.05436759232543409
  lightness: 0.4799663280136883
  saturation: 0.787701997673139
  rhythmicContrast: 0.16847963514737785
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.0922707652207464
author:
  name: Perzen Patel
  email: perzen@bawibride.com
name: Bawi Bride Kitchen
title: Taste the Love. Love the Taste.
description: Jamva Chalo Ji
